---
# tasks file for ansible-role-portshaker

- name: "Include {{ ansible_os_family }}.yml"
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Include install-{{ ansible_os_family }}.yml"
  include: "install-{{ ansible_os_family }}.yml"

- name: Create portshaker_mirror_base_dir
  file:
    path: "{{ portshaker_mirror_base_dir }}"
    mode: 0755
    owner: "{{ portshaker_user }}"
    group: "{{ portshaker_group }}"
    state: directory

- name: Create portshaker_portsnap_dir
  file:
    path: "{{ portshaker_portsnap_dir }}"
    owner: "{{ portshaker_user }}"
    group: "{{ portshaker_group }}"

- name: Create or remove portshaker_ports_dirs
  file:
    access_time: "{{ item.file.access_time | default(omit) }}"
    access_time_format: "{{ item.file.access_time_format | default(omit) }}"
    attributes: "{{ item.file.attributes | default(omit) }}"
    follow: "{{ item.file.follow | default(omit) }}"
    force: "{{ item.file.force | default(omit) }}"
    group: "{{ item.file.group | default(omit) }}"
    mode: "{{ item.file.mode | default(omit) }}"
    modification_time: "{{ item.file.modification_time | default(omit) }}"
    modification_time_format: "{{ item.file.modification_time_format | default(omit) }}"
    owner: "{{ item.file.owner | default(omit) }}"
    path: "{{ item.file.path }}"
    recurse: "{{ item.file.recurse | default(omit) }}"
    src: "{{ item.file.src | default(omit) }}"
    state: "{{ item.file.state | default(omit) }}"
    unsafe_writes: "{{ item.file.unsafe_writes | default(omit) }}"
  with_items: "{{ portshaker_ports_trees }}"

- name: Create portshaker.conf
  template:
    src: portshaker.conf.j2
    dest: "{{ portshaker_conf_file }}"
    validate: sh -n %s
