---
# tasks file for ansible-role-portshaker

- include_vars: "{{ ansible_os_family }}.yml"

- include: "install-{{ ansible_os_family }}.yml"

- name: Create log directory
  file:
    path: "{{ portshaker_log_dir }}"
    mode: 0755
    owner: "{{ portshaker_user }}"
    group: "{{ portshaker_group }}"
    state: directory
  notify: Restart portshaker

- name: Create db directory
  file:
    path: "{{ portshaker_db_dir }}"
    mode: 0755
    owner: "{{ portshaker_user }}"
    group: "{{ portshaker_group }}"
    state: directory
  notify: Restart portshaker

- name: Create portshaker.conf
  template:
    src: portshaker.conf.j2
    dest: "{{ portshaker_conf_file }}"
    validate: echo %s
  notify: Restart portshaker

- name: Start portshaker
  service:
    name: "{{ portshaker_service }}"
    enabled: true
    state: started
